#!/bin/sh -e
#
# Activate Bluetooth for Variscite DART-6UL / VAR-SOM-MX7
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.

som=dart-6ul
tuple_num=0x80

if [ "$som" = "dart-6ul" ]
then
	gpio_num=132
	tty_dev=ttymxc1
elif [ "$som" = "var-som-mx7" ]
then
	gpio_num=14
	tty_dev=ttymxc2
else
	exit 1
fi

(dmesg | grep -q "tuple $tuple_num") # Check if BT/WIFI is up
if [ $? -eq 0 ]
then
	echo "BT found"
fi

echo $gpio_num >/sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio${gpio_num}/direction
echo 0 > /sys/class/gpio/gpio${gpio_num}/value
sleep 0.1
echo 1 > /sys/class/gpio/gpio${gpio_num}/value

brcm_patchram_plus --patchram /lib/firmware/bcm/bcm43430a1.hcd  --enable_hci --bd_addr 64:a3:cb:5b:69:f0 --no2bytes --tosleep 1000 /dev/${tty_dev} &

sleep 2

/usr/lib/bluez5/bluetooth/bluetoothd &

hciconfig hci0 up

exit 0
