#!/bin/sh -e
#
# variscite bluetooth 
#
# This script is executed at the end of each multiuser runlevel.
# Make sure that the script will "exit 0" on success or any other
# value on error.
#
# In order to enable or disable this script just change the execution
# bits.
#
# This script activate the Bluetooth for Variscite SOM MX6
# I/O
#
#Check if device exist
#
(dmesg | grep "tuple 0x80") # Check if BT/WIFI is up
if [ $? -eq 0 ]      # check exit code; if 0 No BT else BT
then
    echo "BT found"
  else
    echo "No BT found"
    exit 0
fi
#
echo 132 >/sys/class/gpio/export
echo "out" > /sys/class/gpio/gpio132/direction
echo 0 > /sys/class/gpio/gpio132/value
sleep 1
echo 1 > /sys/class/gpio/gpio132/value
sleep 1
#
brcm_patchram_plus --patchram /lib/firmware/bcm/bcm43430a1.hcd  --enable_hci --bd_addr 64:a3:cb:5b:69:f0 --no2bytes --tosleep 1000 /dev/ttymxc1 &

#hciattach -n /dev/ttymxc1 any 3000000
#
#
#hciattach -t 10 -s 115200 -n /dev/ttymxc1 any 3000000  2> /dev/null
#
#bluetoothd
/usr/lib/bluez5/bluetooth/bluetoothd &
#
hciconfig hci0 up
#
exit 0
